### PR TITLE
Fix incorrect error message

### PR DESCRIPTION
**Pull request by taikhuu**
When there is error, response are passed to chunked and get processed
before it get to handle_error method

### CODE REVIEW

**Comment by sakama** [comment]
I don't know the context but what type of error do you want to avoid?
Can I ask you to add more detail?

And following code doesn't works?
```ruby
response = httpclient.get(ENDPOINT_EXPORT, params)
handle_error(response)
```

**Review by sakama — COMMENTED** [review]
I don't know the context but what type of error do you want to avoid?
Can I ask you to add more detail?

And following code doesn't works?
```ruby
response = httpclient.get(ENDPOINT_EXPORT, params)
handle_error(response)
```

**Comment by taikhuu** [comment]
Previously the code expect httpclient to not call the pass in blocks when there is error. But it still call the block. Therefor when there is authenticate error, the passed in block still call, it expect the result key and throw another exception before it reach handle_error method.

**Comment by taikhuu** [comment]
@uu59  Could you please help me take a look at this one too ?

**Comment by uu59** [comment]
I think code will work as expected, but probably we need to test for large response without streaming processing.

**Comment by taikhuu** [comment]
@uu59  Sorry, I didn't check that the code block is for stream processing. Added it back along with error handling code

**Review by uu59 — APPROVED** [review]
👍

**Pull request merged**
